### ISSUE TITLE
slice length unknown

### ISSUE THREAD

**Issue by nikkolasg** [dedis/fixbuf#1]
When deserializing a slice, the slice must already be allocated to the right size. Put it in another way, the length is not transmitted in the fixbuf encoding.
While in itself, this is not problem, I envision that the usability is greatly reduced because of that. Imagine a complex hierarchy of structure, it would be impractical to instantiate every intermediate structure to "just" allocate a slice to the right slice.
Therefore, I'd like to raise the question whether we should embed the length of any slice in the encoding.

**Comment by jeffallen** [comment]
Points can now be self-describing. This is no longer an issue.
