### ISSUE TITLE
license

### ISSUE THREAD

**Issue by tobowers** [dedis/fixbuf#4]
Hiyo!

It appears that this code is also used in Kyber which has the MPL license: https://github.com/dedis/kyber/blob/master/LICENSE . I assume that the Kyber license is probably the intended license (since it's a bigger project). Do you think you could re-release this project as MPL as well?

**Comment by jeffallen** [comment]
Yes, this is correct. Our general strategy is that Kyber and it's DEDIS-derived dependencies should be liberally licensed (free to use in all contexts, including closed-source), and Cothority and Onet should be licensed as free software (free = freedom for users to read and modify).
